require('dotenv').config();

const MY_AIRTABLE_API_KEY=process.env.MY_AIRTABLE_API_KEY;
const AIRTABLE_BASE_ID=process.env.AIRTABLE_BASE_ID;
const AIRTABLE_TABLE=process.env.AIRTABLE_TABLE;

const ALGOLIA_APPLICATION_ID=process.env.ALGOLIA_APPLICATION_ID;
const ALGOLIA_API_KEY=process.env.ALGOLIA_API_KEY;
const ALGOLIA_INDEX=process.env.ALGOLIA_INDEX;

module.exports = {
  MY_AIRTABLE_API_KEY,
  AIRTABLE_BASE_ID,
  AIRTABLE_TABLE,
  ALGOLIA_APPLICATION_ID,
  ALGOLIA_API_KEY,
  ALGOLIA_INDEX
}